[2025-05-16T08:04:50.584+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: brewery_pipeline.extract_bronze_data manual__2025-05-16T08:04:47.813585+00:00 [queued]>
[2025-05-16T08:04:50.591+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: brewery_pipeline.extract_bronze_data manual__2025-05-16T08:04:47.813585+00:00 [queued]>
[2025-05-16T08:04:50.592+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-05-16T08:04:50.608+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract_bronze_data> on 2025-05-16 08:04:47.813585+00:00
[2025-05-16T08:04:50.612+0000] {standard_task_runner.py:57} INFO - Started process 34 to run task
[2025-05-16T08:04:50.614+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'brewery_pipeline', 'extract_bronze_data', 'manual__2025-05-16T08:04:47.813585+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/brewery_pipeline.py', '--cfg-path', '/tmp/tmpv8vtswqo']
[2025-05-16T08:04:50.616+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask extract_bronze_data
[2025-05-16T08:04:50.632+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:193 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-16T08:04:50.680+0000] {task_command.py:416} INFO - Running <TaskInstance: brewery_pipeline.extract_bronze_data manual__2025-05-16T08:04:47.813585+00:00 [running]> on host 477fbce01ca2
[2025-05-16T08:04:50.804+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mateus' AIRFLOW_CTX_DAG_ID='brewery_pipeline' AIRFLOW_CTX_TASK_ID='extract_bronze_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-16T08:04:47.813585+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-16T08:04:47.813585+00:00'
[2025-05-16T08:04:50.878+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/brewery_pipeline.py", line 33, in extract_bronze_data
    with open(output_path, 'w') as f:
PermissionError: [Errno 13] Permission denied: '/opt/airflow/data/bronze/breweries_raw.json'
[2025-05-16T08:04:50.888+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=brewery_pipeline, task_id=extract_bronze_data, execution_date=20250516T080447, start_date=20250516T080450, end_date=20250516T080450
[2025-05-16T08:04:50.913+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task extract_bronze_data ([Errno 13] Permission denied: '/opt/airflow/data/bronze/breweries_raw.json'; 34)
[2025-05-16T08:04:50.947+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-16T08:04:50.973+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
